[build]
  publish = "dist"

[[redirects]]
  from = "/es"
  to = "/es"
  status = 200
  force = true

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy"
  status = 200
  force = true

[[redirects]]
  from = "/vntotxt-free"
  to = "/vntotxt-free"
  status = 200
  force = true

[[redirects]]
  from = "/vntotxt-pro"
  to = "/vntotxt-pro"
  status = 200
  force = true

[[redirects]]
  from = "/es/vntotxt-pro"
  to = "/es/vntotxt-pro"
  status = 200
  force = true

[[redirects]]
  from = "/es/vntotxt-free"
  to = "/es/vntotxt-free"
  status = 200
  force = true
